// SPDX-FileCopyrightText: Copyright (c) 2026 ChipFlow Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! GF180MCU standard-cell library support.
//!
//! Sibling of [`crate::sky130`]; together with [`crate::gf180mcu_pdk`] this
//! module provides cell detection, pin direction, and library identification
//! for GlobalFoundries' open-source 180 nm MCU PDK across both
//! `gf180mcu_fd_sc_mcu7t5v0` (7-track, 5 V) and `gf180mcu_fd_sc_mcu9t5v0`
//! (9-track, 5 V) standard-cell libraries.
//!
//! Cell-name convention:
//! `gf180mcu_fd_sc_<track>__<celltype>_<drive>`
//! e.g. `gf180mcu_fd_sc_mcu7t5v0__nand2_1`.
//!
//! IO pads (`gf180mcu_fd_io__*`), primitives (`gf180mcu_fd_pr__*`), and IP
//! blocks (`gf180mcu_fd_ip_*__*`) all share the `gf180mcu_fd_` prefix and
//! are detected as GF180MCU here so the netlist parser doesn't reject them;
//! cell-type extraction is conservative and only strips the standard-cell
//! prefixes. Decomposition for non-standard-cell families lands in later
//! phases per `docs/plans/gf180mcu-enablement.md`.

use compact_str::CompactString;
use netlistdb::{Direction, LeafPinProvider};
use sverilogparse::SVerilogRange;

// Generated by build.rs from the vendored cell-model submodules.
// Provides `GF180MCU_PIN_TABLE: &[(&str, &[(&str, Direction)])]`.
include!(concat!(env!("OUT_DIR"), "/gf180mcu_pins.rs"));

/// All GF180MCU cell instantiations share this prefix.
const GF180MCU_PREFIX: &str = "gf180mcu_fd_";

const SC_7T_PREFIX: &str = "gf180mcu_fd_sc_mcu7t5v0__";
const SC_9T_PREFIX: &str = "gf180mcu_fd_sc_mcu9t5v0__";

/// Is `name` any GF180MCU cell — standard cell, IO pad, primitive, or IP?
pub fn is_gf180mcu_cell(name: &str) -> bool {
    name.starts_with(GF180MCU_PREFIX)
}

/// Strip the GF180MCU library prefix and the trailing drive-strength
/// suffix to recover the base cell type.
///
/// `gf180mcu_fd_sc_mcu7t5v0__nand2_1` → `nand2`.
/// `gf180mcu_fd_sc_mcu9t5v0__inv_20` → `inv`.
///
/// Non-standard-cell families (IO, PR, IP) return the suffix after the
/// library prefix verbatim — decomposition for those lands in later
/// phases.
pub fn extract_cell_type(name: &str) -> &str {
    let stripped = name
        .strip_prefix(SC_7T_PREFIX)
        .or_else(|| name.strip_prefix(SC_9T_PREFIX))
        .unwrap_or(name);

    // Drive strength is always a numeric tail after the final underscore
    // — matches the SKY130 convention.
    if let Some(last_underscore) = stripped.rfind('_') {
        let suffix = &stripped[last_underscore + 1..];
        if !suffix.is_empty() && suffix.chars().all(|c| c.is_ascii_digit()) {
            return &stripped[..last_underscore];
        }
    }

    stripped
}

/// LeafPinProvider for GF180MCU standard cells.
///
/// All cell pins are scalar (no bus pins), so `width_of` returns `None`.
/// Non-standard-cell families (IO pads, primitives, IP) are recognised
/// by [`is_gf180mcu_cell`] for detection purposes but absent from the
/// generated pin table — instantiating one here is a panic until later
/// phases stub in port directions for those families.
pub struct GF180MCULeafPins;

impl LeafPinProvider for GF180MCULeafPins {
    fn direction_of(
        &self,
        macro_name: &CompactString,
        pin_name: &CompactString,
        _pin_idx: Option<isize>,
    ) -> Direction {
        let cell_type = extract_cell_type(macro_name);
        for (ct, pins) in GF180MCU_PIN_TABLE {
            if *ct == cell_type {
                for (p, d) in *pins {
                    if *p == pin_name.as_str() {
                        return *d;
                    }
                }
                panic!(
                    "Unknown gf180mcu pin on cell type '{cell_type}': \
                     macro={macro_name}, pin={pin_name}",
                );
            }
        }
        panic!(
            "Unknown gf180mcu cell (no pin-table entry for type '{cell_type}'): \
             macro={macro_name}",
        );
    }

    fn width_of(
        &self,
        _macro_name: &CompactString,
        _pin_name: &CompactString,
    ) -> Option<SVerilogRange> {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_standard_cells_in_both_variants() {
        assert!(is_gf180mcu_cell("gf180mcu_fd_sc_mcu7t5v0__nand2_1"));
        assert!(is_gf180mcu_cell("gf180mcu_fd_sc_mcu9t5v0__nand2_1"));
    }

    #[test]
    fn detects_io_pr_and_ip_families() {
        assert!(is_gf180mcu_cell("gf180mcu_fd_io__bi_24t"));
        assert!(is_gf180mcu_cell("gf180mcu_fd_pr__nmos_3p3"));
        assert!(is_gf180mcu_cell("gf180mcu_fd_ip_sram__sram64x16m8wm1"));
    }

    #[test]
    fn rejects_non_gf180mcu_names() {
        assert!(!is_gf180mcu_cell("sky130_fd_sc_hd__nand2_1"));
        assert!(!is_gf180mcu_cell("AND2_00_0"));
        assert!(!is_gf180mcu_cell(""));
        assert!(!is_gf180mcu_cell("gf180mcu"));
    }

    #[test]
    fn extracts_base_cell_type_across_variants() {
        assert_eq!(extract_cell_type("gf180mcu_fd_sc_mcu7t5v0__inv_1"), "inv");
        assert_eq!(extract_cell_type("gf180mcu_fd_sc_mcu7t5v0__inv_20"), "inv");
        assert_eq!(extract_cell_type("gf180mcu_fd_sc_mcu9t5v0__nand2_4"), "nand2");
        assert_eq!(extract_cell_type("gf180mcu_fd_sc_mcu9t5v0__dffq_1"), "dffq");
        assert_eq!(
            extract_cell_type("gf180mcu_fd_sc_mcu7t5v0__aoi222_1"),
            "aoi222"
        );
    }

    #[test]
    fn extraction_handles_dff_with_polarity_in_name() {
        // The 'n' in dffnq / dffnrnq is part of the cell type, not a
        // drive-strength suffix — the drive number is the trailing _1.
        assert_eq!(extract_cell_type("gf180mcu_fd_sc_mcu7t5v0__dffnq_1"), "dffnq");
        assert_eq!(extract_cell_type("gf180mcu_fd_sc_mcu7t5v0__dffnrsnq_2"), "dffnrsnq");
    }

    #[test]
    fn extraction_passes_through_unprefixed_names() {
        // Unprefixed names still get numeric-suffix stripping.
        assert_eq!(extract_cell_type("inv_1"), "inv");
        // Non-numeric tails are left intact — no false trim.
        assert_eq!(extract_cell_type("not_a_cell"), "not_a_cell");
        assert_eq!(extract_cell_type("plain"), "plain");
    }

    #[test]
    fn pin_table_covers_full_cell_catalogue() {
        // 7t and 9t share an identical 69-cell catalogue per the gf180mcu
        // README; the generated table is deduped by base cell type, so we
        // expect exactly 69 entries.
        assert_eq!(GF180MCU_PIN_TABLE.len(), 69, "expected 69 cell types");
    }

    #[test]
    fn pin_provider_returns_expected_directions() {
        let provider = GF180MCULeafPins;
        let dir = |cell: &str, pin: &str| {
            provider.direction_of(
                &CompactString::from(cell),
                &CompactString::from(pin),
                None,
            )
        };
        // Spot-check across cell families.
        assert_eq!(dir("gf180mcu_fd_sc_mcu7t5v0__inv_1", "I"), Direction::I);
        assert_eq!(dir("gf180mcu_fd_sc_mcu7t5v0__inv_20", "ZN"), Direction::O);
        assert_eq!(dir("gf180mcu_fd_sc_mcu9t5v0__nand2_4", "A1"), Direction::I);
        assert_eq!(dir("gf180mcu_fd_sc_mcu9t5v0__nand2_4", "ZN"), Direction::O);
        assert_eq!(dir("gf180mcu_fd_sc_mcu7t5v0__dffq_1", "CLK"), Direction::I);
        assert_eq!(dir("gf180mcu_fd_sc_mcu7t5v0__dffq_1", "D"), Direction::I);
        assert_eq!(dir("gf180mcu_fd_sc_mcu7t5v0__dffq_1", "Q"), Direction::O);
        // notifier is in the cell's port list — must be modeled as an input
        // so synthesis output naming it doesn't reject as unknown.
        assert_eq!(dir("gf180mcu_fd_sc_mcu7t5v0__dffq_1", "notifier"), Direction::I);
    }

    #[test]
    fn pin_provider_handles_both_variants_identically() {
        let provider = GF180MCULeafPins;
        for cell in ["aoi22_1", "dffrnq_1", "mux2_1"] {
            let pin = "Q"; // not all of these have Q; only DFF does — we'll branch
            let _ = pin;
            let pin_in = match cell {
                "aoi22_1" => "A1",
                "dffrnq_1" => "CLK",
                "mux2_1" => "I0",
                _ => unreachable!(),
            };
            let macro_7t = CompactString::from(format!("gf180mcu_fd_sc_mcu7t5v0__{cell}"));
            let macro_9t = CompactString::from(format!("gf180mcu_fd_sc_mcu9t5v0__{cell}"));
            let pin_cs = CompactString::from(pin_in);
            assert_eq!(
                provider.direction_of(&macro_7t, &pin_cs, None),
                provider.direction_of(&macro_9t, &pin_cs, None),
                "7t/9t disagreed on {cell}.{pin_in}",
            );
        }
    }

    #[test]
    fn pin_provider_width_is_always_scalar() {
        let provider = GF180MCULeafPins;
        // No bus pins in the standard-cell library.
        assert!(provider
            .width_of(
                &CompactString::from("gf180mcu_fd_sc_mcu7t5v0__nand2_1"),
                &CompactString::from("A1"),
            )
            .is_none());
    }

    #[test]
    fn aig_builds_from_combinational_gf180mcu_netlist() {
        // End-to-end: gf180mcu Verilog → NetlistDB → AIG. Exercises
        // the full Phase 4 path: GF180MCULeafPins, library detection,
        // load_pdk_models, decompose_combinational, AIG integration.
        const VERILOG: &str = r#"
module tiny(A, B, C, Y, Z);
  input A, B, C;
  output Y, Z;
  wire mid;
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 u1 (.A1(A), .A2(B), .ZN(mid));
  gf180mcu_fd_sc_mcu9t5v0__inv_1   u2 (.I(mid), .ZN(Y));
  gf180mcu_fd_sc_mcu7t5v0__or3_1   u3 (.A1(A), .A2(B), .A3(C), .Z(Z));
endmodule
"#;
        let nl = netlistdb::NetlistDB::from_sverilog_source(
            VERILOG,
            Some("tiny"),
            &GF180MCULeafPins,
        )
        .expect("netlist parse");
        let aig = crate::aig::AIG::from_netlistdb(&nl);
        // NAND2 + INV cancel out (NAND followed by INV = AND), and OR3
        // decomposes to a chain of AND gates with input/output inversion.
        // Exact AIG-pin count varies with synthesis choices; just assert
        // construction succeeded and produced a non-empty AIG.
        assert!(aig.num_aigpins > 0, "AIG should have at least one pin");
    }

    #[test]
    fn netlist_db_round_trips_a_mixed_7t_9t_design() {
        // Exercise the full LeafPinProvider contract through NetlistDB —
        // catches missing pin entries, mis-typed directions, and any
        // bus-width assumption the parser makes.
        const VERILOG: &str = r#"
module tiny(A, B, CLK, Y, Q);
  input A, B, CLK;
  output Y, Q;
  wire mid, q1, notifier;
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 u1 (.A1(A), .A2(B), .ZN(mid));
  gf180mcu_fd_sc_mcu9t5v0__inv_1   u2 (.I(mid), .ZN(Y));
  gf180mcu_fd_sc_mcu7t5v0__dffq_1  u3 (.CLK(CLK), .D(mid), .Q(q1), .notifier(notifier));
  gf180mcu_fd_sc_mcu9t5v0__inv_1   u4 (.I(q1), .ZN(Q));
endmodule
"#;
        let nl = netlistdb::NetlistDB::from_sverilog_source(VERILOG, Some("tiny"), &GF180MCULeafPins);
        assert!(nl.is_some(), "NetlistDB construction failed");
    }
}
